### PR TITLE
instance of adjustments

### PR DESCRIPTION
**Pull request by sebotic**

### CODE REVIEW

**Comment by stuppie** [comment]
Will get_sub_ontology work if the item is new? It won't yet be in Wikidata yet, and so it won't be able to get the sub_ontology, right?

**Comment by sebotic** [comment]
If the query in get_sub_ontology returns nothing, the for loop will not be entered and the return value of get_sub_ontology will be None, so it will work as expected as self.sub_ontology will stay None

**Comment by stuppie** [comment]
But then there will be no "instance of" claim on that item, right?

**Comment by sebotic** [comment]
for the top-level, there should not be one anyway, but for all other levels there will be one as soon as the sparql endpoint has the sub-ontology item id. At latest at the second bot run, all ontology terms will have the proper instance of subclass.

**Pull request merged**
